### PR TITLE
Initial class structure and methods

### PR DESCRIPTION
**Pull request by pgoulding**
@thatpamIam @robbiejaeger

created class structure, added methods and tests to prepare for DOM implementation.

### CODE REVIEW

**Review by ArAprojects — COMMENTED** [review]
Class names look good, structure should be easy to understand!

**Review by ArAprojects — COMMENTED** [review]
Good job using Linter.

**Review by JellyBeans1312 — COMMENTED** [review]
Love the math.random(). adding and subtracting is a good lil way to pick 3 surveys

**Review by JellyBeans1312 — COMMENTED** [review]
'This' as a parameter is muy caliente

**Review by pgoulding — COMMENTED** [review]
I like this solution for instantiating new players on the Game Start

**Review by ArAprojects — APPROVED** [review]
Class structure is organized and tests are well written.

**Pull request merged**
