### PR TITLE
New dom updates

### PR DESCRIPTION
**Pull request by JellyBeans1312**

### CODE REVIEW

**Review by pgoulding — CHANGES_REQUESTED** [review]
Great job on the timeout function! On index.js lines 59,61, and 64 you could just use "turn" instead of 'round.turn', and on line 33 of index.js, game_board is actually game-board in the HTML. Could you implement these changes?

**Comment by JellyBeans1312** [comment]
OH!! yeah you're right. ill change those real quick

**Comment by JellyBeans1312** [comment]
should be good to go

**Review by pgoulding — APPROVED** [review]

**Comment by pgoulding** [comment]
Awesome, thanks for fixing that!

**Pull request merged**
